name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  firebase_auth: ^3.0.1
  firebase_cloud_interfaces:
    path: ../firebase_cloud/interfaces
  firebase_core: ^1.4.0
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.5
  sign_in_with_apple: ^3.0.0
  very_good_analysis: 2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
