name: form_inputs
description: A Dart package which exposes reusable form inputs and validation rules
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  formz: ^0.4.0
  intl: ^0.17.0

dev_dependencies:
  test: ^1.16.4
  very_good_analysis: 2.3.0
