name: firebase_cloud_interfaces
description: Interfaces and models
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.2
  intl: ^0.17.0
  json_annotation: ^4.0.1
  very_good_analysis: 2.3.0

dev_dependencies:
  build_runner: ^2.0.4
  coverage: ^1.0.3
  json_serializable: ^4.1.3
  mockito: ^5.0.10
  mocktail: ^0.1.4
  test: ^1.17.9
