name: app_config_repository
description: Dart package which manages the app configuration domain.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.0
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  very_good_analysis: ^2.3.0

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.3
  mocktail: ^0.1.4
